import subprocess
import sys

cmd = [
    sys.executable,
    "-u",
    "run.py",
    "--task_name",
    "long_term_forecast",
    "--is_training",
    "1",
    "--root_path",
    "./datasets/ETT-small/",
    "--data_path",
    "ETTh1.csv",
    "--model_id",
    "ETTh1_MS_96_720",
    "--model",
    "TINA",
    "--data",
    "ETTh1",
    "--features",
    "MS",
    "--target",
    "OT",
    "--freq",
    "h",
    "--seq_len",
    "96",
    "--label_len",
    "48",
    "--pred_len",
    "720",
    "--enc_in",
    "7",
    "--dec_in",
    "7",
    "--c_out",
    "7",
    "--d_model",
    "256",
    "--d_ff",
    "768",
    "--n_heads",
    "4",
    "--e_layers",
    "2",
    "--factor",
    "1",
    "--patch_len",
    "8",
    "--na_kernel_size",
    "9",
    "--batch_size",
    "32",
    "--patience",
    "3",
    "--learning_rate",
    "0.0007339387616994463",
    "--dropout",
    "0.12304281196389771",
    "--lradj",
    "type3",
    "--activation",
    "relu",
    "--train_epochs",
    "5",
    "--num_workers",
    "0",
    "--itr",
    "1",
    "--des",
    "Exp",
]

if __name__ == "__main__":
    print("Running TINA on ETTh1 MS with pred_len=720")
    print("=" * 60)
    subprocess.run(cmd)
